eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8020
      name: user-service
server:
  port: 8082
